variable "env" {}
variable "vpc_cidr" {}
variable "public_subnet" {}
variable "web_subnet" {}
variable "app_subnet" {}
variable "db_subnet" {}
variable "azs" {}
variable "account_no" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_vpc_route_table_id" {}
variable "bastion_node_cidr" {}